project:
  type: website
execute:
    freeze: auto  # this ensures code is only re-run when its specific .qmd file changes
    echo: false

website:
  site-url: "https://jon-kane.github.io/justan3ngin33r"
  favicon: "images/logo_gray.png"
  navbar:
    logo: "images/logo_cropped.png"
    logo-href: "https://buymeacoffee.com/justan3ngin33r"
    left:
      - href: index.qmd
        text: home
      - href: writings.qmd
        text: writings

format:
  html:
    theme: cyborg
    page-layout: article
    toc: true
    toc-title: "on the page"
    language: 
      code-links-title: "get the code"
    code-fold: true
    date-format: long
    css: styles.css
    reference-location: margin
    citation-location: margin

